# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b694e8520a37d025250f2a47722b3a45b7f91004b36ecaefb29af117feb91569ef3ef9c9e6359426ba45ca4248b8ce2ec3fbbdd586b6dffd73c6372b88b9a1d0

test:
  secret_key_base: ef14fc608f648ac078e7ee31fb0a4c7a589d352b9e25cbf1a878c135401f74794fe484e69d4b3423fcf7e66fcdbc0888907b84241fd380cdb0e8ee49613ef3b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
